### ISSUE TITLE
Your Git for Windows SDK configuration ...

### ISSUE THREAD

**Issue by martin-braun** [zeero/scoop-my-bucket#1]
Hi, I'm learning about scoop currently. Quick question, would https://github.com/zeero/scoop-my-bucket/blob/master/git-for-windows-sdk.json still install into `C:\git-sdk-64`?

**Comment by zeero** [comment]
Hi.
Unfortunately, I haven't touched Windows in the last few years, so I have no idea what's going on these days :(
Sorry I can't help you.

**Comment by martin-braun** [comment]
@zeero Everything is fine. You cannot recall and I won't judge you. Thanks for taking the time out of your day to respond me anyways. :)
